### ISSUE TITLE
A question about coordinates and rendering after fusion. 

### ISSUE THREAD

**Issue by mah-asd** [GAP-LAB-CUHK-SZ/GaussReg#11]
Hi, thank you for providing the code. 
I have a question about the coordinate systems in scene A and B. When you train separately, is the pose for the first frame in each scene identity matrix? Then you find the transformation and transform the point cloud B to the coordinate of A. Is the rendering result for scene B after transformation good? 
As far as I searched, there is no quality result for the rendered images after fusing, right?

**Comment by Jiahao620** [comment]
No, since I driectly use colmap to calculate the camera poses of each scene, the pose for the first frame in each scene is not identity matrix;
The rendering result for scene B after transformation is good, you can try it with our gs_fusion.py;
You can see the comparsion results of rendered videos before and after fusing in our project page, there is no difference in rendering results.

**Comment by mah-asd** [comment]
Thank you for your reply; that makes total sense. 

I'm trying to train GS for only one scene and then transfer the coordinates using an arbitrary transformation matrix for points and poses. Then, I will render based on newly transferred poses, but the rendering result is not good. The poses seem correct, but the quality is not the same as before the transformation. Do you have any idea about this?

**Comment by Jiahao620** [comment]
The problem of rendering quality may be due to the pseudo inverse.  We state that in section 3.4 of our paper, "Note that, it is difficult to choose vectors u_{0}, ..., u_{2i+1} to ensure that Q is invertible, so in our experiments, we use the pseudo inverse as an approximation to inverse while calculating Q^{−1}".

**Comment by mah-asd** [comment]
As far as I know (correct me if I'm wrong) the transformation matrix (4x4 including R and t) is designed to be non-singular all the time and so the regular inverse functions in python can find the exact inverse.  

I have another question about fusing, with this approach that when a point is closer to the center of points will remain in the merged map, it might make some part of map get deleted while it shouldn't. For example,
 in this attached image, the star point is closer to the center of the other point cloud, but it will be removed. 

![IMG_0572](https://github.com/user-attachments/assets/500fec24-e55f-49f8-afce-51da1f386b08)

**Comment by Jiahao620** [comment]
Note that here Q is the transformation matrix of spherical harmonics (SH) coefficients rather than the the transformation matrix you mentioned.
You can compute the distance from each point to its closest camera optical center instead of the distance from each point to its scene center, which can alleviate this problem.

**Comment by mah-asd** [comment]
Thank you so much for answering my question, that's a great idea.
